# Generated by Django 3.2.3 on 2021-06-01 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sequence',
            fields=[
                ('namecode', models.CharField(max_length=300, primary_key=True, serialize=False)),
                ('sequence', models.TextField()),
            ],
        ),
    ]
