# Generated by Django 3.2.3 on 2021-06-02 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('namecode1', models.CharField(max_length=300)),
                ('namecode2', models.CharField(max_length=300)),
                ('align_sequence', models.TextField()),
                ('image', models.CharField(max_length=300)),
            ],
        ),
    ]
